server:
  port: 8080

spring:
  application:
    name: campus-food-backend
  config:
    import: optional:classpath:application-local.yaml

mybatis:
  configuration:
    map-underscore-to-camel-case: true